### ISSUE TITLE
code

### ISSUE THREAD

**Issue by shajie17** [dkulon/hand-reconstruction#1]
hello,it's already May 2019,when will you release the code?
I'm waiting for you,thank you

**Comment by dkulon** [comment]
Thank you for your patience. It will be released by the end of the month. Hopefully, this weekend. Please, note that the pre-print was published in May.

**Comment by momo1986** [comment]
I am not sure whether depth image is needed for this project's data training?

**Comment by dkulon** [comment]
> I am not sure whether depth image is needed for this project's data training?

The training data consists of RGB images, triangular meshes, and landmarks for camera estimation.

https://arxiv.org/abs/1905.01326

**Comment by momo1986** [comment]
Hello @dkulon , is it convenient for you to publish the training data and code if you think it OK?

Can I understand that it only needs one single RGB image with hand during inference?

Thanks & Regards!

**Comment by dkulon** [comment]
Yes, the code will be published this month. During inference the system requires only an RGB image.

**Comment by dkulon** [comment]
The code and data will be released later after the paper is officially announced in a conference/journal. I was not aware of the convention. Thank you for waiting.

Best,
Dominik

**Comment by momo1986** [comment]
Hello, could the code and model be public if it was convenient to @dkulon ？

**Comment by dkulon** [comment]
The code, models, and data have been made publicly available.
