### ISSUE TITLE
it seems the trained model hasn't released? thanks

### ISSUE THREAD

**Issue by visonpon** [dkulon/hand-reconstruction#4]

**Comment by dkulon** [comment]
Hi,

The trained model is in ./data/models/i2m/1555053417.5808766.base/models/ and the example of loading is in the Jupyter notebook in ./evaluation/i2m.ipynb. A link to the data directory is in the README.md file.

Best,
Dominik

**Comment by visonpon** [comment]
oh, i didn't realize the ` Hand Reconstruction Data` contain trained model, sorry for bother you, thanks~
