### ISSUE TITLE
Hope know how to test on arbitraty image

### ISSUE THREAD

**Issue by visonpon** [dkulon/hand-reconstruction#5]
Hi, @dkulon , according to your detailed readme, I have got an excellent result for the data you provided, but I also curious about how to test on my own image.
Are there any examples of how to prepare or process my own image in order to test the model? thanks~

**Comment by dkulon** [comment]
Hey, @visonpon, you can replace a provided data loader with your custom code, for example, with a `placeholder` for an image. Please, note that the model was trained only on a CMU dataset with images captured in a laboratory setting so it might not generalise to other domains.

Best,
Dominik
