### ISSUE TITLE
Use my own hand, Seems not good

### ISSUE THREAD

**Issue by FighterFong** [dkulon/hand-reconstruction#6]
hi, author
The result seems not good when i use my own hand image, only modify input hand image(not modify hand 2D&3D keypoint). Seems the generated mesh pose not like the real hand(Such as figure2). Can you reply it? Thanks.

![Screenshot 2019-12-11 at 4 09 32 PM](https://user-images.githubusercontent.com/20882610/70603431-7deed200-1c31-11ea-90d0-a2521ecc97ad.png)
![Screenshot 2019-12-11 at 4 14 02 PM](https://user-images.githubusercontent.com/20882610/70603542-ba223280-1c31-11ea-8d40-a0f928e867ee.png)

**Comment by visonpon** [comment]
@FighterFong I also got similar results on my own image, it seems the results depend heavily on the J_regressor.npy, mean_points.npy, and std_points.npy provided by the author, which means that we have to train the model from start. and get those files from our own datasets.

**Comment by dkulon** [comment]
@FighterFong @visonpon 
The training input images were cropped based on ground truth annotations. The network is therefore sensitive to the position of the hand in the image crop. This can be resolved by using data augmentation during training - random cropping and shifts. 

There is also a domain gap as the training data consists of HD images taken in a laboratory setting from a third-person perspective (http://domedb.perception.cs.cmu.edu/index.html) while your images, @FighterFong, were taken from an egocentric perspective. However, your examples are simple so the first issue is more likely to be the main cause.

**Comment by nicmeniconi** [comment]
@FighterFong @visonpon What were the steps needed to try it on your own image.If you could share your modified data loading code I would deeply appreciate it.  I am sorry I come from a pytorch background and it is not straightforward.
