### ISSUE TITLE
How to make trilist.npy

### ISSUE THREAD

**Issue by FighterFong** [dkulon/hand-reconstruction#7]
Hi, author,
I was confused that how to make trilist.npy file. I also want to know how to make it although you publish it.

**Comment by dkulon** [comment]
Hi @FighterFong,

The `trillst.npy` contains a NumPy array with mesh triangulation data. The triangulation is taken directly from a template mesh provided by an artist or its downsampled versions (https://github.com/dkulon/hand-reconstruction/blob/master/utils/downsample_template_py27.ipynb).

**Comment by FighterFong** [comment]
Hi, author,
Do yo know how to make the template mesh file which provided by an artist. Seems use  some 3D edit software like maya?

**Comment by dkulon** [comment]
@FighterFong, that’s one of the options.
