### ISSUE TITLE
implement question 

### ISSUE THREAD

**Issue by quyanqiu** [dkulon/hand-reconstruction#9]
Just a little question about your CVPR2020 article "hands in the wild":
How you treat left hand model and right hand model in your spiral mesh Convolution layer? The spiral convolution should do mesh sampling and generate spiral sequence offline before train the network,
Did you treat them seperately?
The same problem occurs when use iterative fitting when generating ground truth mesh,For left hand
image,you use MANO LEFT Hand model and for right hand image you use MANO Right Hand model?
I know this issue is unrelated to this project,but it is very kind of you if you can make a reply. Thx!

**Comment by dkulon** [comment]
Hi @quyanqiu ,

We only use a left hand model for the neural network. If an image contains a right hand, we mirror the input image and afterwards we mirror output vertices.

For the iterative fitting, we also load a hand model corresponding to one side and we negate X vertex coordinates if we need to fit the other hand side.

**Comment by quyanqiu** [comment]
@dkulon thanks a lot mate！
It help a lot for me to implement your paper,thanks again!
